name: Java CI For Project
	on:
	  push:
	    branches: [ master ]
	

	jobs:
	  build-deploy-run:
	

	    runs-on: ubuntu-latest
	

	    steps:
	    - uses: actions/checkout@v2
	    - name: Set up JDK 1.14
	      uses: actions/setup-java@v1
	      with:
	        java-version: 1.14
	    - name: Build with Maven
	      run: |
	        #sudo bash ./setenv.sh application.stage
	        mvn clean install
	        #curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline started"}' https://hooks.slack.com/services/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
	              
	    - name: copy file via ssh key
	      uses: appleboy/scp-action@master
	      with:
	        host: 13.233.150.190 
	        username: ubuntu
	        key: ${{ secrets.key }}
	        source: "target/*.jar"
	        target: "builds"
	        
	    - name: SSH Remote Commands
	      uses: appleboy/ssh-action@v0.1.3
	      with:
	        host: 13.233.150.190 
	        username: ubuntu
	        key: ${{ secrets.key }}
	        script: |
	          fuser -k -n tcp 8080
	          fuser -k -n tcp 8080
	          fuser -k -n tcp 8080
	          fuser -k -n tcp 8080
	          #sudo systemctl restart /usr/lib/systemd/system/javaapp.service
	          java -jar /home/ubuntu/builds/target/*.jar > /home/ubuntu/builds/target/server-logs.txt 2>&1 &
	

